@startuml

interface Generator {
    next()
}

class Fib

Generator <.. Fib

interface Iterable

class IteratorFib

Iterable <.. IteratorFib

Fib <|-- IteratorFib


interface Iterator
Iterable <|.. Iterator


@enduml